"use strict";
const $ = id => document.getElementById(id);
const node = (tag, cls, value) => {const n=document.createElement(tag);if(cls)n.className=cls;if(value!==undefined)n.textContent=String(value);return n;};
const addFact = (target,label,value) => {const item=node('div','advanced-fact');item.append(node('span','muted',label),node('strong','',value??'Unknown'));target.append(item);};
const names = value => ({'cline-free/muse-spark-1.3-contributor':'Muse Spark 1.3','z-ai/glm-5.3-flash':'GLM 5.3 Flash','cline-free/deepseek-v4.1-flash':'DeepSeek V4.1 Flash'})[value]||String(value||'Unknown').split('/').pop().replace(/-/g,' ');
const ago = time => !time?'No evidence':Math.max(0,Math.floor((Date.now()-Number(time))/60000))+'m ago';
const goalName = id => ({'1452826a-661e-4a0d-b88a-6054c2de5a25':'Shiftio','1c2ccdda-855a-4d2c-b75d-4897b31ae8d1':'CMO dashboard','goal-cmo-trustworthy-20260919':'CMO migration ? legacy'})[id]||'Saved Goal';
function classification(cell){if(!cell)return ['unknown','No evidence'];if(cell.state==='AVAILABLE'&&cell.freshness==='fresh')return ['good','Recently verified'];if(cell.state==='QUOTA'&&(!cell.reset_at||Number(cell.reset_at)>Date.now()))return ['bad','Quota exhausted'];if(cell.state==='AUTH_BLOCKED')return ['bad','Sign-in required'];if(cell.state==='CAPABILITY_UNAVAILABLE')return ['bad','Not offered'];if(cell.state==='QUOTA_EXPIRED'||cell.state==='QUOTA')return ['pending','Cooldown passed ? recheck needed'];if(cell.state==='AVAILABLE')return ['pending','Success expired ? recheck needed'];return ['unknown',cell.state==='TRANSIENT'?'Provider error':'Unknown ? recheck needed'];}
async function load(){try{const response=await fetch('/api/snapshot',{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);const snap=await response.json();$('connection').textContent='Connected';$('connection').className='status good';
 const matrix=$('matrix');matrix.replaceChildren();const accounts=[...(snap.policy?.accounts||[])].sort((a,b)=>(a.priority??0)-(b.priority??0));let ready=0,quota=0,pending=0,unknown=0;
 for(const route of snap.free_matrix||[]){const box=node('div','advanced-model');box.append(node('h3','',names(route.model)));const cells=node('div','advanced-account-grid');for(const account of accounts){if(account.enabled===false)continue;const cell=route.accounts?.[account.id];const [kind,label]=classification(cell);if(kind==='good')ready++;if(kind==='bad')quota++;if(kind==='pending')pending++;if(kind==='unknown')unknown++;const item=node('div','advanced-cell '+kind);item.append(node('strong','',account.id.replace('account-','Account ')),node('span','',label),node('small','',cell?.reset_at&&kind==='bad'?'Reset reported: '+new Date(Number(cell.reset_at)).toLocaleString():'Last observation: '+ago(cell?.observed_at)));cells.append(item);}box.append(cells);matrix.append(box);}
 $('route-count').textContent=(snap.free_matrix||[]).length+' models';$('route-summary').textContent=ready?`${ready} verified free routes ? ${quota} blocked ? ${pending} need recheck ? ${unknown} unknown`:`No free route recently verified ? ${quota} blocked ? ${pending} need recheck ? ${unknown} unknown`;
 const goals=$('goals');goals.replaceChildren();for(const goal of snap.goals||[]){const item=node('div','advanced-goal');const detail=node('div');detail.append(node('strong','',goalName(goal.goal_id)),node('small','',`Saved: ${goal.status||'unknown'} ? observed ${ago(goal.last_activity_at)}`));item.append(detail,node('span','work-status '+(goal.display_status==='blocked'?'bad':''),goal.display_status||'Unverified'));goals.append(item);}if(!goals.children.length)goals.append(node('p','muted','No saved Goals.'));
 const facts=$('service-info');facts.replaceChildren();addFact(facts,'Service',snap.service?.status||'Unknown');addFact(facts,'Last event',snap.service?.last_event_received_iso||'None');addFact(facts,'State revision',snap.state_revision);addFact(facts,'Policy version',snap.policy?.version);addFact(facts,'Artifact',String(snap.service?.artifact_digest||'Unknown').slice(0,12));
 const events=$('events');events.replaceChildren();for(const event of (snap.recent_events||[]).slice(0,15)){const line=node('div','advanced-event');line.append(node('strong','',event.event_type||'Event'),node('span','',event.reason_code||'No reason code'));events.append(line);}if(!events.children.length)events.append(node('p','muted','No recent events.'));
 const catalog=$('catalog-info');catalog.replaceChildren();addFact(catalog,'Provider catalog',snap.freshness?.catalog_status||'Unknown');addFact(catalog,'Model entries',(snap.catalog||[]).length);addFact(catalog,'Policy digest',String(snap.policy?.digest||'Unknown').slice(0,12));
 }catch(error){$('connection').textContent='Disconnected';$('connection').className='status bad';$('route-summary').textContent='Unable to refresh diagnostics: '+error.message;}}
$('refresh').addEventListener('click',load);load();setInterval(load,15000);
